### ISSUE TITLE
Erigon setup config values

### ISSUE THREAD

**Issue by jacquesvcritien** [okx/Deploy#3]
What should the values for zkevm.l2-datastreamer-url be for testnet and mainnet please?

**Comment by zjg555543** [comment]
**mainnet**: stream.xlayer.tech:8800
**testnet**: teststream.xlayer.tech:8800
**demo config:**
[xlayerconfig-testnet.yaml.example](https://github.com/okx/xlayer-erigon/blob/release/v0.3.1/xlayerconfig-testnet.yaml.example)
[xlayerconfig-mainnet.yaml.example](https://github.com/okx/xlayer-erigon/blob/release/v0.3.1/xlayerconfig-mainnet.yaml.example)
